### PR TITLE
Issue 1 provide bet probabilities given a card configuration

### LINKED ISSUE #1: Provide bet probabilities given a card configuration
To allow any AI design to efficiently assess the base probabilities of occurrence of a bet, create a module to handle the probability vector computation/assembly.

### PR DESCRIPTION
**Pull request by adrian-golian**
Closes #1

### CODE REVIEW

**Comment by adrian-golian** [comment]
@maciej-pomykala , I encourage you to try this code out - as far as I can see, it works:
```
>>> from shared.probabilities import handler
>>> h = handler.Handler()
>>> h.get_probability_vector(cards=[(4,3),(5,1),(0,2),(0,0),(1,3),(2,3),(3,3),(5,3)], others_card_num=3)
array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.48928571, 0.48928571, 0.48928571,
       0.48928571, 1.        , 0.48928571, 0.48928571, 0.19285714,
       0.48928571, 0.19285714, 0.19285714, 0.48928571, 0.19285714,
       0.19285714, 0.19285714, 1.        , 0.48928571, 0.48928571,
       0.48928571, 0.48928571, 1.        , 1.        , 1.        ,
       0.35      , 0.07142857, 0.07142857, 0.07142857, 0.07142857,
       0.35      , 0.13392857, 0.13392857, 0.13392857, 0.13392857,
       0.35      , 0.07142857, 0.01607143, 0.01607143, 0.01607143,
       0.07142857, 0.07142857, 0.01607143, 0.01607143, 0.01607143,
       0.07142857, 0.07142857, 0.01607143, 0.01607143, 0.01607143,
       0.07142857, 0.07142857, 0.01607143, 0.01607143, 0.01607143,
       0.07142857, 0.35      , 0.13392857, 0.13392857, 0.13392857,
       0.13392857, 0.        , 0.        , 0.        , 1.        ,
       0.025     , 0.00178571, 0.00178571, 0.00178571, 0.00178571,
       0.025     , 0.00178571, 0.        , 0.00178571, 0.1875    ,
       0.        , 0.00178571, 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.1875    ])
>>> h.get_probability_vector(cards=[(4,3),(5,1),(0,2),(0,0)], others_card_num=3)
array([1.00000000e+00, 5.08771930e-01, 5.08771930e-01, 5.08771930e-01,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 8.77192982e-02,
       8.77192982e-02, 8.77192982e-02, 4.03508772e-01, 4.03508772e-01,
       8.77192982e-02, 8.77192982e-02, 0.00000000e+00, 8.77192982e-02,
       0.00000000e+00, 0.00000000e+00, 4.03508772e-01, 1.57894737e-02,
       1.57894737e-02, 1.57894737e-02, 4.03508772e-01, 1.57894737e-02,
       1.57894737e-02, 1.57894737e-02, 1.26315789e-01, 5.61403509e-02,
       5.61403509e-02, 5.61403509e-02, 2.84210526e-01, 3.50877193e-03,
       3.50877193e-03, 3.50877193e-03, 4.56140351e-02, 4.56140351e-02,
       1.05263158e-02, 1.05263158e-02, 1.05263158e-02, 8.68421053e-02,
       8.68421053e-02, 3.50877193e-03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.50877193e-03, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50877193e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       4.56140351e-02, 7.89473684e-03, 7.89473684e-03, 7.89473684e-03,
       7.89473684e-03, 4.56140351e-02, 7.89473684e-03, 7.89473684e-03,
       7.89473684e-03, 7.89473684e-03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.57894737e-02, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 8.77192982e-04, 8.77192982e-04,
       8.77192982e-04, 0.00000000e+00, 8.77192982e-04, 8.77192982e-04,
       0.00000000e+00, 8.77192982e-04, 0.00000000e+00, 8.77192982e-04,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])
```

**Comment by adrian-golian** [comment]
Ok, I think something's wrong with the straights and full houses 3K, in edge conditions, will fix:
```
>>> h.get_probability_vector(cards=[(4,3)], others_card_num=23)
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])
>>> h.get_probability_vector(cards=[(4,3), (5,1),(0,2),(0,0)], others_card_num=20)
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])
```

**Comment by adrian-golian** [comment]
Fixed both issues:
```
>>> h.get_probability_vector(cards=[(0,3)], others_card_num=23)
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])
>>> h.get_probability_vector(cards=[(4,3), (3,3),(2,3),(1,1)], others_card_num=20)
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])
```

**Review by maciej-pomykala — APPROVED** [review]
Got it to work, don't see obvious mistakes.

**Pull request merged**
